name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Забрать код
        uses: actions/checkout@v5

      - name: Установить Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Установить poetry
        run: pip install poetry

      - name: Установить зависимости
        run: poetry install --no-interaction --no-root

      - name: Запустить тесты с покрытием
        env:
          SECRET_KEY: test_secret_key
          ACCESS_TOKEN_EXPIRE_MINUTES: "30"
          ALGORITHM: HS256
          DB_USER: test_user
          DB_PASSWORD: test_password
          DB_NAME: test_db
          DB_HOST: localhost
          DB_PORT: "5432"
        run: poetry run pytest -vv -ra --maxfail=1 --tb=short --cov=src --cov-report=term-missing